name = "herbahero"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "43b22e2dda544b28a8377f316fd09af0"

[vars]
MEDIA_BASE_URL = "https://media.herbahero.my.id"

[[routes]]
pattern = "herbahero.my.id/*"
zone_name = "herbahero.my.id"
